#server:
#  port: 8081
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/parishpro
#    username: root
#    password: pass
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#logging:
#  level:
#    com.newwayus.parishpro.controller: DEBUG
#    org.hibernate: ERROR
#  org.hibernate.SQL: OFF